### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by joshopdev** [Assaro/DD_Bot#16] opened 2022-12-16 21:20 UTC
When I change the whitelist to true and add my id to both the admin and the userid sections I get the following error:

"You are not allowed to use this command" in discord.

When I turn off the whitelist it works just fine.

**Comment by Assaro** [comment] 2022-12-17 09:25
Odd that this occurs. Never checked the case of someone being in the user and the admin List. Please tell me the command that gives you this error and also send me your settings. You may have entered something in a wrong way

**Comment by joshopdev** [comment] 2022-12-19 23:19
Running just the /list command would give the error and it would be the same for all users. When it was just me in the admin list and I was not listed in the user list I would get that error. When I was listed in both the admin and user lists I would get that error. The only way to have it work was to disable the whitelist.

This is my settings.json file. (it has been sanitized) 

`  "LanguageSettings": {
    "Language": "en"
  },
  "DiscordSettings": {
    "Token": "MPN1BnQg_MyToken_KJJRSDKsdfoi23jlk32",
    "AdminIDs": [
      0951235052641524
    ],
    "UserWhitelist": true,
    "UserIDs": [
      0951235052641524,
      041170438009625,
      831669290250515
    ],
    "UsersCanStopContainers": true,
    "AllowedContainers": [
      "ECO"
    ]
  },
  "DockerSettings": {
    "BotName": "DD_Bot",
    "Retries": 6,
    "TimeBeforeRetry": 5
  }
}
`

**Comment by Assaro** [comment] 2022-12-21 08:16
Weird. Probably had something wrong. I will check it out and release a bugfix as soon as possible

**Comment by Assaro** [comment] 2022-12-21 09:10
I uploaded a potential fix. Please pull the docker-image DD_Bot:bugfix and report whether that fixes your problem. Will port to release if successful on your side

**Comment by Assaro** [comment] 2022-12-29 12:15
Assuming that no reply means the issue is fixed i will now close this issue

**Closed** 2022-12-29 12:15 UTC
Labels: bug
